version: "3.8"
services:
  app:
    image: node:24-slim
    command: npm run dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
