name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: install, lint, build
        run: |
          docker compose run --rm app /bin/bash -c "npm i && npm run lint && npm run build"
