name: auto-merge
on:
  pull_request_target:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: install, lint, build
        run: |
          docker-compose run --rm app /bin/bash -c "npm i && npm run lint && npm run build"

  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: test
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        id: merge
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: |
          result=$(gh pr merge --auto --merge "$PR_URL")
          echo "::set-output name=merge_result::$result"
        continue-on-error: true
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment failed reasons
        if: ${{ steps.merge.outcome != 'success' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Auto-merge failed for this PR.
            Message: ${{ steps.merge.outputs.merge_result }}
